spring:
  application:
    name: monkey_finance
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
server:
  port: 8080