spring:
  application:
    name: monkey_finance
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
server:
  port: 8080