# profile for local development

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev
  security:
    user:
      # noinspection SpellCheckingInspection
      name: devuser
      # noinspection SpellCheckingInspection
      password: devuser123

  datasource:
    url: jdbc:postgresql://localhost:5432/monkey_finance_dev
    username: monkey_finance_app
    password: ${DB_APP_PASSWORD}

  liquibase:
    enabled: true
    user: monkey_migrate
    password: ${DB_MIGRATE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE