package com.lin.monkey_finance.domain.ledger.model;

public enum LedgerActionType {
    MEMBER_INVITED,
    USER_DECLINED_INVITATION,
    MEMBER_INVITATION_REVOKED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_BLOCKED,
    MEMBER_UNBLOCKED,
    MEMBER_ACCESS_TYPE_CHANGED,
    OWNERSHIP_TRANSFERRED,
    MEMBER_DELETED,
    CATEGORY_EDITED,
    CATEGORY_CREATED,
    CATEGORY_DELETED,
    CATEGORY_SETTINGS_ADDED,
    CATEGORY_SETTINGS_EDITED,
    CATEGORY_SETTINGS_DELETED,
    SUBCATEGORY_ADDED,
    SUBCATEGORY_EDITED,
    SUBCATEGORY_DELETED,
    ACCOUNT_ADDED,
    ACCOUNT_EDITED,
    ACCOUNT_DELETED
}
